### ISSUE TITLE
Add eligibility criteria, for clarity?

### ISSUE THREAD

**Issue by SteveBarnett** [RailsBridge-CapeTown/rails-bridge-capetown.github.com#33]
Like http://codebar.io/faq#attendance-eligibility .

**Comment by rorymckinley** [comment]
@SteveBarnett I thought we did already - but I see the meetup.com pages says "groups of people that are underrepresented in tech" are the target. I am happy for us to make that more explicit!

**Comment by SteveBarnett** [comment]
@rorymckinley Yeah, I dig what you're wrapping, but we still get people signing up who _don't_ meet the eligibility criteria, and I think I'd like to be able to point to something specific on our site.

**Comment by SteveBarnett** [comment]
https://github.com/RailsBridge-CapeTown/rails-bridge-capetown.github.com/pull/34
